layout_name= "Wariat B"
layout_screen_w=1600
layout_screen_h=900
vetical_bar_right_w_offset = layout_screen_w*0.8
horizontal_bar_height_offset = layout_screen_h*0.75
vertical_bar_left_w_offset = layout_screen_w*0.6
box_offset_w = 10
box_offset_h = 10
box_w = layout_screen_w*0.6-20
box_h = layout_screen_h*0.75-20